#!/usr/bin/env bash

#-------------------------------------------------------------------------------
# Author     : Florian Hild
# Created    : 16-05-2025
# Description: Extract tar files
#-------------------------------------------------------------------------------

export LANG=C

if [[ "${0}" == "${BASH_SOURCE[0]}" ]]; then
  echo "This script must be sourced, not executed." >&2
  exit 1
fi

function extract_tar() {
    local tar_file="${1}"
    local dst_path="${2}"
    shift 2
    local tar_opts=("${@}")

    if ! command -v tar >/dev/null 2>&1; then
        log "error" "\"tar\" command not found."
        exit 1
    fi

    if [[ ! -f "${tar_file}" ]]; then
        log "error" "File not found: \"${tar_file}\""
        exit 1
    else
        mkdir -p "${dst_path}"

        log "info" "Extracting \"${tar_file}\" to \"${dst_path}\"..."
        tar -x -v "${tar_opts[@]}" -f "${tar_file}"  -C "${dst_path}"
    fi
}
